### ISSUE TITLE
internal link in section edit 

### ISSUE THREAD

**Issue by kavodao** [zioth/dokuwiki_fastwiki#42]
When editing a section and using the button for an internal link, the window open but the sintax of the internal link never write.

**Comment by zioth** [comment]
Sorry for the long delay. This is now fixed.

**Comment by jmchantrein** [comment]
Hello. I still see this problem. Apparently, I'm not alone: https://forum.dokuwiki.org/d/20458-internal-link-wizard-not-working. Thanks for your work.

**Comment by zioth** [comment]
Thanks for letting me know. Reopening the issue.

**Comment by zioth** [comment]
Fixed!

**Comment by jmchantrein** [comment]
Thank you ! It works.

**Comment by sifriede** [comment]
Dear zioth, I am facing this issue again. The date in plugin.info.txt says "2024-02-10". I've tried with opera and firefox browser. If I disable the fastwiki plugin, the internal link wizard works.

**Comment by jeffxt** [comment]
Bumping this old thread.  Also seeing the same issue - the internal link button will not show the dialog box when you press on it.  This happens only in section edit mode.  If you disable that, the link button works just fine.  

Any chance this can get updated?  Still love this plugin!
